from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

COMMON_CONTRACT_CONTEXT = (
    "!LICENSE",
    "!packages",
    "packages/*",
    "!packages/contracts",
    "packages/contracts/*",
    "!packages/contracts/pyproject.toml",
    "!packages/contracts/src",
    "packages/contracts/src/*",
    "!packages/contracts/src/stonks_contracts",
    "packages/contracts/src/stonks_contracts/*",
    "!packages/contracts/src/stonks_contracts/*.py",
    "!packages/contracts/src/stonks_contracts/py.typed",
)
SERVICE_AUTH_CONTEXT = (
    "!packages/service-auth",
    "packages/service-auth/*",
    "!packages/service-auth/pyproject.toml",
    "!packages/service-auth/src",
    "packages/service-auth/src/*",
    "!packages/service-auth/src/stonks_service_auth",
    "packages/service-auth/src/stonks_service_auth/*",
    "!packages/service-auth/src/stonks_service_auth/*.py",
    "!packages/service-auth/src/stonks_service_auth/py.typed",
)
EXPECTED_CONTEXTS = {
    "sidecars/nautilus/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        *SERVICE_AUTH_CONTEXT,
        "!sidecars",
        "sidecars/*",
        "!sidecars/__init__.py",
        "!sidecars/nautilus",
        "sidecars/nautilus/*",
        "!sidecars/nautilus/Dockerfile",
        "!sidecars/nautilus/NOTICE.md",
        "!sidecars/nautilus/__init__.py",
        "!sidecars/nautilus/adapter.py",
        "!sidecars/nautilus/app.py",
        "!sidecars/nautilus/distribution-manifest.yaml",
        "!sidecars/nautilus/engine.py",
        "!sidecars/nautilus/pyproject.toml",
        "!sidecars/nautilus/runtime_app.py",
        "!sidecars/nautilus/uv.lock",
        "!scripts",
        "scripts/*",
        "!scripts/smoke_nautilus.py",
    ),
    "sidecars/lean/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        *SERVICE_AUTH_CONTEXT,
        "!sidecars",
        "sidecars/*",
        "!sidecars/__init__.py",
        "!sidecars/lean",
        "sidecars/lean/*",
        "!sidecars/lean/Dockerfile",
        "!sidecars/lean/NOTICE.md",
        "!sidecars/lean/__init__.py",
        "!sidecars/lean/adapter.py",
        "!sidecars/lean/app.py",
        "!sidecars/lean/appsettings.template.json",
        "!sidecars/lean/distribution-manifest.yaml",
        "!sidecars/lean/dotnet-locks",
        "!sidecars/lean/dotnet-locks/**",
        "!sidecars/lean/engine.py",
        "!sidecars/lean/engine",
        "!sidecars/lean/engine/**",
        "!sidecars/lean/patches",
        "!sidecars/lean/patches/**",
        "!sidecars/lean/pyproject.toml",
        "!sidecars/lean/runtime_app.py",
        "!sidecars/lean/uv.lock",
        "!scripts",
        "scripts/*",
        "!scripts/smoke_lean.py",
    ),
    "workers/tradingagents/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        *SERVICE_AUTH_CONTEXT,
        "!workers",
        "workers/*",
        "!workers/__init__.py",
        "!workers/tradingagents",
        "workers/tradingagents/*",
        "!workers/tradingagents/NOTICE.md",
        "!workers/tradingagents/__init__.py",
        "!workers/tradingagents/adapter.py",
        "!workers/tradingagents/app.py",
        "!workers/tradingagents/artifacts.py",
        "!workers/tradingagents/pyproject.toml",
        "!workers/tradingagents/runtime.py",
        "!workers/tradingagents/runtime_app.py",
        "!workers/tradingagents/uv.lock",
    ),
    "workers/kronos/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        *SERVICE_AUTH_CONTEXT,
        "!workers",
        "workers/*",
        "!workers/__init__.py",
        "!workers/kronos",
        "workers/kronos/*",
        "!workers/kronos/NOTICE.md",
        "!workers/kronos/__init__.py",
        "!workers/kronos/adapter.py",
        "!workers/kronos/app.py",
        "!workers/kronos/model-manifest.json",
        "!workers/kronos/model_loader.py",
        "!workers/kronos/profiles",
        "workers/kronos/profiles/*",
        "!workers/kronos/profiles/cuda",
        "workers/kronos/profiles/cuda/*",
        "!workers/kronos/profiles/cuda/pyproject.toml",
        "!workers/kronos/profiles/cuda/uv.lock",
        "!workers/kronos/pyproject.toml",
        "!workers/kronos/runtime_app.py",
        "!workers/kronos/uv.lock",
    ),
    "workers/quant_lab/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        *SERVICE_AUTH_CONTEXT,
        "!config",
        "config/*",
        "!config/workers",
        "config/workers/*",
        "!config/workers/quant_lab.yaml",
        "!workers",
        "workers/*",
        "!workers/__init__.py",
        "!workers/quant_lab",
        "workers/quant_lab/*",
        "!workers/quant_lab/Dockerfile",
        "!workers/quant_lab/NOTICE.md",
        "!workers/quant_lab/__init__.py",
        "!workers/quant_lab/app.py",
        "!workers/quant_lab/pyproject.toml",
        "!workers/quant_lab/qlib_adapter.py",
        "!workers/quant_lab/runtime_app.py",
        "!workers/quant_lab/uv.lock",
    ),
    "workers/quant_lab/rd_agent/Dockerfile.dockerignore": (
        *COMMON_CONTRACT_CONTEXT,
        "!workers",
        "workers/*",
        "!workers/__init__.py",
        "!workers/quant_lab",
        "workers/quant_lab/*",
        "!workers/quant_lab/__init__.py",
        "!workers/quant_lab/rd_agent",
        "workers/quant_lab/rd_agent/*",
        "!workers/quant_lab/rd_agent/CVE_REVIEW.md",
        "!workers/quant_lab/rd_agent/Dockerfile",
        "!workers/quant_lab/rd_agent/NOTICE.md",
        "!workers/quant_lab/rd_agent/__init__.py",
        "!workers/quant_lab/rd_agent/adapter.py",
        "!workers/quant_lab/rd_agent/candidate_runner.py",
        "!workers/quant_lab/rd_agent/cli.py",
        "!workers/quant_lab/rd_agent/distribution-manifest.yaml",
        "!workers/quant_lab/rd_agent/grype.yaml",
        "!workers/quant_lab/rd_agent/openvex.json",
        "!workers/quant_lab/rd_agent/pyproject.toml",
        "!workers/quant_lab/rd_agent/runner.py",
        "!workers/quant_lab/rd_agent/sandbox_policy.yaml",
        "!workers/quant_lab/rd_agent/uv.lock",
    ),
}


def test_root_context_images_have_exact_dockerfile_specific_allowlists() -> None:
    root_ignore = (ROOT / ".dockerignore").read_text(encoding="utf-8").splitlines()
    assert {"scripts", "sidecars", "workers"} <= set(root_ignore)

    for relative_path, expected in EXPECTED_CONTEXTS.items():
        lines = (ROOT / relative_path).read_text(encoding="utf-8").splitlines()
        assert lines == ["**", *expected]


def test_openbb_ci_build_passes_exact_checkout_revision() -> None:
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    assert workflow.count('--build-arg "VCS_REF=$GITHUB_SHA"') == 1
