"""core_data

Revision ID: 0001
Revises:
Create Date: 2026-07-11 03:43:52.937559
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPEND_ONLY_TABLES = (
    "artifact_manifest",
    "evidence_item",
    "evidence_edge",
    "dataset_snapshot",
    "run_event",
    "inbox",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_manifest",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("license_tag", sa.String(length=128), nullable=False),
        sa.Column("sensitivity", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name="artifact_content_hash_format"
        ),
        sa.CheckConstraint("size_bytes >= 0", name="artifact_size_nonnegative"),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "inbox",
        sa.Column("consumer", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("consumer", "message_id"),
    )
    op.create_table(
        "instrument",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("primary_symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange_mic", sa.String(length=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="instrument_version_positive"),
        sa.PrimaryKeyConstraint("instrument_id"),
        sa.UniqueConstraint(
            "exchange_mic",
            "primary_symbol",
            "valid_from",
            name="uq_instrument_primary_identity",
        ),
    )
    op.create_index(
        op.f("ix_instrument_exchange_mic"), "instrument", ["exchange_mic"], unique=False
    )
    op.create_table(
        "outbox",
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("outbox_id"),
        sa.UniqueConstraint(
            "aggregate_type",
            "aggregate_id",
            "sequence",
            name="uq_outbox_aggregate_sequence",
        ),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency_key"),
    )
    op.create_index(
        "ix_outbox_delivery", "outbox", ["published_at", "not_before"], unique=False
    )
    op.create_table(
        "provider_health",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "failure_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("quota_remaining", sa.Integer(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("failure_count >= 0", name="provider_failure_nonnegative"),
        sa.PrimaryKeyConstraint("provider", "capability", "market"),
    )
    op.create_table(
        "run",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0", name="run_version_positive"),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_run_idempotency_key"),
    )
    op.create_index(op.f("ix_run_status"), "run", ["status"], unique=False)
    op.create_table(
        "trading_calendar_version",
        sa.Column("calendar_version_id", sa.UUID(), nullable=False),
        sa.Column("mic", sa.String(length=4), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effective_to is null or effective_to > effective_from",
            name="calendar_effective_window",
        ),
        sa.PrimaryKeyConstraint("calendar_version_id"),
        sa.UniqueConstraint("mic", "version", name="uq_calendar_mic_version"),
    )
    op.create_index(
        op.f("ix_trading_calendar_version_mic"),
        "trading_calendar_version",
        ["mic"],
        unique=False,
    )
    op.create_table(
        "usage_budget",
        sa.Column("budget_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hard_limit", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("used", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("hard_limit >= 0", name="budget_limit_nonnegative"),
        sa.CheckConstraint("period_end > period_start", name="budget_period_valid"),
        sa.CheckConstraint("used >= 0", name="budget_used_nonnegative"),
        sa.CheckConstraint("version > 0", name="budget_version_positive"),
        sa.PrimaryKeyConstraint("budget_id"),
        sa.UniqueConstraint(
            "scope", "period_start", "period_end", name="uq_budget_scope_period"
        ),
    )
    op.create_table(
        "dataset_snapshot",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_policy_id", sa.String(length=128), nullable=False),
        sa.Column("manifest_artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_hash"],
            ["artifact_manifest.content_hash"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        op.f("ix_dataset_snapshot_as_of"), "dataset_snapshot", ["as_of"], unique=False
    )
    op.create_table(
        "evidence_item",
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "availability_certainty",
            sa.String(length=16),
            server_default=sa.text("'proven'"),
            nullable=False,
        ),
        sa.Column(
            "strict_point_in_time",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("quality_state", sa.String(length=32), nullable=False),
        sa.Column("sensitivity", sa.String(length=32), nullable=False),
        sa.Column("license_tag", sa.String(length=128), nullable=False),
        sa.Column("redistribution_tag", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name="evidence_content_hash_format"
        ),
        sa.CheckConstraint(
            "not strict_point_in_time or availability_certainty = 'proven'",
            name="evidence_strict_availability_proven",
        ),
        sa.CheckConstraint(
            "available_at <= observed_at", name="evidence_available_by_observed"
        ),
        sa.CheckConstraint(
            "not strict_point_in_time or available_at <= as_of",
            name="evidence_available_by_as_of",
        ),
        sa.ForeignKeyConstraint(
            ["raw_artifact_hash"],
            ["artifact_manifest.content_hash"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        op.f("ix_evidence_item_as_of"), "evidence_item", ["as_of"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_item_available_at"),
        "evidence_item",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_item_event_time"),
        "evidence_item",
        ["event_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_item_provider"), "evidence_item", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_item_subject"), "evidence_item", ["subject"], unique=False
    )
    op.create_table(
        "instrument_alias",
        sa.Column("alias_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=128), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "valid_to is null or valid_to > valid_from",
            name="instrument_alias_valid_window",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instrument.instrument_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint(
            "provider",
            "symbol",
            "valid_from",
            name="uq_instrument_alias_provider_symbol_from",
        ),
    )
    op.create_index(
        op.f("ix_instrument_alias_instrument_id"),
        "instrument_alias",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "job",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "attempt_generation",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("attempt_nonce", sa.String(length=128), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_generation >= 0", name="job_generation_nonnegative"
        ),
        sa.CheckConstraint("attempts <= max_attempts", name="job_attempts_within_max"),
        sa.CheckConstraint("attempts >= 0", name="job_attempts_nonnegative"),
        sa.CheckConstraint(
            "deadline_at is null or deadline_at > not_before",
            name="job_deadline_after_not_before",
        ),
        sa.CheckConstraint("max_attempts > 0", name="job_max_attempts_positive"),
        sa.ForeignKeyConstraint(
            ["result_artifact_hash"],
            ["artifact_manifest.content_hash"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_job_idempotency_key"),
    )
    op.create_index(
        "ix_job_claim", "job", ["status", "not_before", "lease_until"], unique=False
    )
    op.create_index(op.f("ix_job_job_type"), "job", ["job_type"], unique=False)
    op.create_index(op.f("ix_job_not_before"), "job", ["not_before"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "run_event",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_hash", name="uq_run_event_hash"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_event_sequence"),
    )
    op.create_index(op.f("ix_run_event_run_id"), "run_event", ["run_id"], unique=False)
    op.create_table(
        "evidence_edge",
        sa.Column("parent_evidence_id", sa.UUID(), nullable=False),
        sa.Column("child_evidence_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=64), nullable=False),
        sa.Column("transformation_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "parent_evidence_id <> child_evidence_id", name="evidence_edge_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["child_evidence_id"], ["evidence_item.evidence_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_evidence_id"], ["evidence_item.evidence_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("parent_evidence_id", "child_evidence_id", "relation"),
    )
    # ### end Alembic commands ###
    _create_roles()
    _protect_append_only_tables()
    _grant_least_privilege()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_edge")
    op.drop_index(op.f("ix_run_event_run_id"), table_name="run_event")
    op.drop_table("run_event")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_not_before"), table_name="job")
    op.drop_index(op.f("ix_job_job_type"), table_name="job")
    op.drop_index("ix_job_claim", table_name="job")
    op.drop_table("job")
    op.drop_index(
        op.f("ix_instrument_alias_instrument_id"), table_name="instrument_alias"
    )
    op.drop_table("instrument_alias")
    op.drop_index(op.f("ix_evidence_item_subject"), table_name="evidence_item")
    op.drop_index(op.f("ix_evidence_item_provider"), table_name="evidence_item")
    op.drop_index(op.f("ix_evidence_item_event_time"), table_name="evidence_item")
    op.drop_index(op.f("ix_evidence_item_available_at"), table_name="evidence_item")
    op.drop_index(op.f("ix_evidence_item_as_of"), table_name="evidence_item")
    op.drop_table("evidence_item")
    op.drop_index(op.f("ix_dataset_snapshot_as_of"), table_name="dataset_snapshot")
    op.drop_table("dataset_snapshot")
    op.drop_table("usage_budget")
    op.drop_index(
        op.f("ix_trading_calendar_version_mic"), table_name="trading_calendar_version"
    )
    op.drop_table("trading_calendar_version")
    op.drop_index(op.f("ix_run_status"), table_name="run")
    op.drop_table("run")
    op.drop_table("provider_health")
    op.drop_index("ix_outbox_delivery", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_instrument_exchange_mic"), table_name="instrument")
    op.drop_table("instrument")
    op.drop_table("inbox")
    op.drop_table("artifact_manifest")
    # ### end Alembic commands ###
    op.execute("drop function if exists reject_append_only_mutation()")


def _create_roles() -> None:
    for role in ("stonks_reader", "stonks_app", "stonks_worker"):
        op.execute(
            f"""
            do $$
            begin
                if not exists (select 1 from pg_roles where rolname = '{role}') then
                    create role {role} nologin;
                end if;
            end
            $$
            """
        )


def _protect_append_only_tables() -> None:
    op.execute(
        """
        create function reject_append_only_mutation()
        returns trigger
        language plpgsql
        as $$
        begin
            raise exception 'table % is append-only', tg_table_name
                using errcode = '55000';
        end
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"""
            create trigger trg_{table}_append_only
            before update or delete on {table}
            for each row execute function reject_append_only_mutation()
            """
        )


def _grant_least_privilege() -> None:
    op.execute("revoke all on all tables in schema public from public")
    op.execute(
        "grant usage on schema public to stonks_reader, stonks_app, stonks_worker"
    )
    op.execute("grant select on all tables in schema public to stonks_reader")
    op.execute("grant select on all tables in schema public to stonks_app")
    op.execute(
        """
        grant insert on artifact_manifest, evidence_item, evidence_edge,
            dataset_snapshot, run_event, inbox
        to stonks_app
        """
    )
    op.execute(
        """
        grant select, insert, update on instrument, instrument_alias,
            trading_calendar_version, run, job, outbox, provider_health, usage_budget
        to stonks_app
        """
    )
    op.execute(
        """
        grant select, insert on artifact_manifest, run_event, inbox
        to stonks_worker
        """
    )
    op.execute(
        """
        grant select, insert, update on job, outbox
        to stonks_worker
        """
    )
