"""Versioned, execution-safe wire contracts for Stonks Agent."""

from .common import SCHEMA_VERSION, ContractModel, ModelUsage, Money, stable_payload_hash
from .evidence import EvidenceItem, EvidencePack
from .execution import (
    ExecutionCommand,
    ExecutionReceipt,
    Fill,
    JournalPosting,
    JournalTransaction,
    OrderIntent,
)
from .instrument import InstrumentKey, ProviderSymbol
from .kronos import (
    KronosBar,
    KronosForecastPath,
    KronosForecastPoint,
    KronosRuntimeIdentity,
    KronosSamplePathsArtifact,
    KronosSamplingPolicy,
    KronosWorkerRequest,
    KronosWorkerResponse,
    KronosWorkerResult,
    VolumeQuality,
)
from .market_data import Bar, BarSeries, DataQuality, DatasetSnapshot, MarketDataQuery
from .portfolio import (
    CashBalance,
    MarketPrice,
    PortfolioSnapshot,
    PortfolioTarget,
    Position,
    TargetAllocation,
)
from .quant_lab import (
    QuantBacktestPosition,
    QuantCostModelSpec,
    QuantDatasetArtifact,
    QuantDatasetRow,
    QuantFeatureSpec,
    QuantLabelSpec,
    QuantMetric,
    QuantModelSpec,
    QuantPrediction,
    QuantResearchJob,
    QuantResearchResult,
    QuantRuntimeIdentity,
    QuantSplitSpec,
    QuantUniverseSpec,
    QuantWorkerResponse,
)
from .report import (
    AnalysisReport,
    ClaimCertainty,
    ReportClaim,
    ReportReference,
    ReportRendering,
)
from .research import (
    AgentOpinion,
    AnalysisBundle,
    Citation,
    ResearchArtifact,
    ResearchClaim,
    ResearchRequest,
)
from .risk import AccountReservation, RiskCheck, RiskDecision
from .signal import AlphaSignal, ForecastSignal
from .tradingagents import (
    SignedEvidenceArtifact,
    TradingAgentsWorkerRequest,
    TradingAgentsWorkerResponse,
    TradingAgentsWorkerResult,
)
from .workflow import Run, RunEvent

CANONICAL_CHAIN = (
    "EvidenceItem/ResearchArtifact",
    "AnalysisBundle/AgentOpinion/AlphaSignal/ForecastSignal",
    "PortfolioTarget",
    "RiskDecision",
    "AccountReservation",
    "OrderIntent",
    "ExecutionReceipt/Fill",
    "JournalTransaction",
    "AnalysisReport",
)

SCHEMA_MODELS: tuple[type[ContractModel], ...] = (
    Money,
    ModelUsage,
    ProviderSymbol,
    InstrumentKey,
    DataQuality,
    MarketDataQuery,
    Bar,
    BarSeries,
    DatasetSnapshot,
    EvidenceItem,
    EvidencePack,
    ResearchRequest,
    ResearchClaim,
    Citation,
    ResearchArtifact,
    AnalysisBundle,
    AgentOpinion,
    ForecastSignal,
    AlphaSignal,
    CashBalance,
    Position,
    MarketPrice,
    PortfolioSnapshot,
    TargetAllocation,
    PortfolioTarget,
    RiskCheck,
    RiskDecision,
    AccountReservation,
    OrderIntent,
    ExecutionCommand,
    ExecutionReceipt,
    Fill,
    JournalPosting,
    JournalTransaction,
    Run,
    RunEvent,
    ReportRendering,
    ReportReference,
    AnalysisReport,
    ReportClaim,
    SignedEvidenceArtifact,
    TradingAgentsWorkerRequest,
    TradingAgentsWorkerResponse,
    TradingAgentsWorkerResult,
    KronosBar,
    KronosSamplingPolicy,
    KronosRuntimeIdentity,
    KronosWorkerRequest,
    KronosForecastPoint,
    KronosForecastPath,
    KronosWorkerResult,
    KronosWorkerResponse,
    KronosSamplePathsArtifact,
    QuantFeatureSpec,
    QuantLabelSpec,
    QuantUniverseSpec,
    QuantCostModelSpec,
    QuantSplitSpec,
    QuantModelSpec,
    QuantRuntimeIdentity,
    QuantDatasetRow,
    QuantDatasetArtifact,
    QuantResearchJob,
    QuantPrediction,
    QuantBacktestPosition,
    QuantMetric,
    QuantResearchResult,
    QuantWorkerResponse,
)

__all__ = [
    "CANONICAL_CHAIN",
    "SCHEMA_MODELS",
    "SCHEMA_VERSION",
    "AccountReservation",
    "AgentOpinion",
    "AlphaSignal",
    "AnalysisBundle",
    "AnalysisReport",
    "BarSeries",
    "ClaimCertainty",
    "ContractModel",
    "DatasetSnapshot",
    "EvidenceItem",
    "EvidencePack",
    "ExecutionCommand",
    "ExecutionReceipt",
    "Fill",
    "ForecastSignal",
    "InstrumentKey",
    "JournalPosting",
    "JournalTransaction",
    "KronosBar",
    "KronosForecastPath",
    "KronosForecastPoint",
    "KronosRuntimeIdentity",
    "KronosSamplePathsArtifact",
    "KronosSamplingPolicy",
    "KronosWorkerRequest",
    "KronosWorkerResponse",
    "KronosWorkerResult",
    "MarketDataQuery",
    "OrderIntent",
    "PortfolioSnapshot",
    "PortfolioTarget",
    "QuantBacktestPosition",
    "QuantCostModelSpec",
    "QuantDatasetArtifact",
    "QuantDatasetRow",
    "QuantFeatureSpec",
    "QuantLabelSpec",
    "QuantMetric",
    "QuantModelSpec",
    "QuantPrediction",
    "QuantResearchJob",
    "QuantResearchResult",
    "QuantRuntimeIdentity",
    "QuantSplitSpec",
    "QuantUniverseSpec",
    "QuantWorkerResponse",
    "ReportClaim",
    "ReportReference",
    "ResearchArtifact",
    "RiskDecision",
    "SignedEvidenceArtifact",
    "TradingAgentsWorkerRequest",
    "TradingAgentsWorkerResponse",
    "TradingAgentsWorkerResult",
    "VolumeQuality",
    "stable_payload_hash",
]
